version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React project...
      - # VITE_API_URL should be set in CodeBuild project environment variables
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
