version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
  build:
    commands:
      - echo Building the React project...
      - # VITE_API_URL will be provided by CodeBuild Environment Variables
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/dist'
